const assets = {
  icons: {
    alignCenter: '/assets/icons/ic_align_center.svg',
    arrowLeft: '/assets/icons/ic_arrow_left.svg',
    arrowRight: '/assets/icons/ic_arrow_right.svg',
    arrowWhite: '/assets/icons/ic_arrow_white.svg',
    bellAlert: '/assets/icons/ic_bell_alert.svg',
    bellEmpty: '/assets/icons/ic_bell_empty.svg',
    calender: '/assets/icons/ic_calender.svg',
    check: '/assets/icons/ic_check.svg',
    checkboxIn: '/assets/icons/ic_checkbox_in.svg',
    checkboxOut: '/assets/icons/ic_checkbox_out.svg',
    diagonal: '/assets/icons/ic_diagonal.svg',
    document: '/assets/icons/ic_document.svg',
    down: '/assets/icons/ic_down.svg',
    eyeOff: '/assets/icons/ic_eye_off.svg',
    eyeOn: '/assets/icons/ic_eye_on.svg',
    filterWhite: '/assets/icons/ic_filter_white.svg',
    firstRankWhite: '/assets/icons/ic_first_rank_white.svg',
    firstRankYellow: '/assets/icons/ic_first_rank_yellow.svg',
    fourthRank: '/assets/icons/ic_fourth_rank.svg',
    giveUp: '/assets/icons/ic_give_up.svg',
    heartActive: '/assets/icons/ic_heart_active.svg',
    heartInactive: '/assets/icons/ic_heart_inactive.svg',
    kebab: '/assets/icons/ic_kebab.svg',
    keyboard: '/assets/icons/ic_keyboard.svg',
    line: '/assets/icons/ic_line.svg',
    list: '/assets/icons/ic_list.svg',
    meatballsMenu: '/assets/icons/ic_meatballs_menu.svg',
    monitor: '/assets/icons/ic_monitor.svg',
    numberList: '/assets/icons/ic_number_list.svg',
    plus: '/assets/icons/ic_plus.svg',
    secondRank: '/assets/icons/ic_second_rank.svg',
    thirdRank: '/assets/icons/ic_third_rank.svg',
    toggleDown: '/assets/icons/ic_toggle_down.svg',
    toggleUp: '/assets/icons/ic_toggle_up.svg',
    up: '/assets/icons/ic_up.svg',
  },
  images: {
    black: '/assets/images/img_black.svg',
    book: '/assets/images/img_book.svg',
    logo: '/assets/images/img_logo.svg',
    profileAdmin: '/assets/images/img_profile_admin.svg',
    profileMember: '/assets/images/img_profile_member.svg',
  },
};
export default assets;
