const assets = {
  icons: {
    arrowDown: '/assets/icons/ic_arrow_down.svg',
    arrowLeftLarge: '/assets/icons/ic_arrow_left_large.svg',
    arrowLeftMedium: '/assets/icons/ic_arrow_left_medium.svg',
    arrowLeftSmall: '/assets/icons/ic_arrow_left_small.svg',
    arrowMainRight: '/assets/icons/ic_arrow_main_right.svg',
    arrowRightLarge: '/assets/icons/ic_arrow_right_large.svg',
    arrowRightMedium: '/assets/icons/ic_arrow_right_medium.svg',
    arrowRightSmall: '/assets/icons/ic_arrow_right_small.svg',
    arrowUp: '/assets/icons/ic_arrow_up.svg',
    bellAlert: '/assets/icons/ic_bell_alert.svg',
    bellEmpty: '/assets/icons/ic_bell_empty.svg',
    crown: '/assets/icons/ic_crown.svg',
    deadlineLarge: '/assets/icons/ic_deadline_large.svg',
    deadlineMedium: '/assets/icons/ic_deadline_medium.svg',
    deadlineSmall: '/assets/icons/ic_deadline_small.svg',
    document: '/assets/icons/ic_document.svg',
    fifthRank: '/assets/icons/ic_fifth_rank.svg',
    filterBlack: '/assets/icons/ic_filter_black.svg',
    filterWhite: '/assets/icons/ic_filter_white.svg',
    firstRankWhite: '/assets/icons/ic_first_rank_white.svg',
    firstRankYellow: '/assets/icons/ic_first_rank_yellow.svg',
    fourthRank: '/assets/icons/ic_fourth_rank.svg',
    heartActive: '/assets/icons/ic_heart_active.svg',
    heartInactive: '/assets/icons/ic_heart_inactive.svg',
    kebab: '/assets/icons/ic_kebab.svg',
    keyboard: '/assets/icons/ic_keyboard.svg',
    list: '/assets/icons/ic_list.svg',
    meatballsMenu: '/assets/icons/ic_meatballs_menu.svg',
    medal: '/assets/icons/ic_medal.svg',
    monitor: '/assets/icons/ic_monitor.svg',
    out: '/assets/icons/ic_out.svg',
    outLarge: '/assets/icons/ic_out_large.svg',
    outMedium: '/assets/icons/ic_out_medium.svg',
    personLarge: '/assets/icons/ic_person_large.svg',
    personMedium: '/assets/icons/ic_person_medium.svg',
    personMediumWhite: '/assets/icons/ic_person_medium_white.svg',
    plusLarge: '/assets/icons/ic_plus_large.svg',
    plusMedium: '/assets/icons/ic_plus_medium.svg',
    search: '/assets/icons/ic_search.svg',
    secondRank: '/assets/icons/ic_second_rank.svg',
    thirdRank: '/assets/icons/ic_third_rank.svg',
    toggleDown: '/assets/icons/ic_toggle_down.svg',
    toggleUp: '/assets/icons/ic_toggle_up.svg',
  },
  images: {
    black: '/assets/images/img_black.svg',
    check: '/assets/images/img_check.svg',
    loginLogoLarge: '/assets/images/img_login_logo_large.svg',
    loginLogoMedium: '/assets/images/img_login_logo_medium.svg',
    loginLogoSmall: '/assets/images/img_login_logo_small.svg',
    navLogoLarge: '/assets/images/img_nav_logo_large.svg',
    navLogoSmall: '/assets/images/img_nav_logo_small.svg',
    profileAdmin: '/assets/images/img_profile_admin.svg',
    profileMember: '/assets/images/img_profile_member.svg',
  },
};

export default assets;
