export const seed = [
  {
    id: 1023,
    docType: 'OFFICIAL',
    field: 'NEXTJS',
    title: 'Next.js - App Router: Routing Fundamentals',
    participates: 3,
    maxParticipates: 5,
    deadline: '2024-12-24T23:59:59',
    progress: false,
  },
  {
    id: 1022,
    docType: 'BLOG',
    field: 'API',
    title: 'Fetch API, 너는 에러를 제대로 핸들링 하고 있는가?(dailydev)',
    participates: 5,
    maxParticipates: 5,
    deadline: '2024-10-23T23:59:59',
    progress: false,
  },
  {
    id: 1021,
    docType: 'OFFICIAL',
    field: 'API',
    title: 'Fetch API, 너는 에러를 제대로 핸들링 하고 있는가?(dailydev)',
    participates: 10,
    maxParticipates: 10,
    deadline: '2024-02-22T23:59:59',
    progress: false,
  },
  {
    id: 1020,
    docType: 'BLOG',
    field: 'CAREER',
    title: '개발자로서 자신만의 브랜드를 구축하는 방법(dailydev)',
    participates: 5,
    maxParticipates: 5,
    deadline: '2024-01-22T23:59:59',
    progress: false,
  },
  {
    id: 1019,
    docType: 'OFFICIAL',
    field: 'NEXTJS',
    title: 'Next.js - App Router: Routing Fundamentals',
    participates: 2,
    maxParticipates: 5,
    deadline: '2024-02-22T23:59:59',
    progress: false,
  },
  {
    id: 1018,
    docType: 'OFFICIAL',
    field: 'API',
    title: 'Fetch API, 너는 에러를 제대로 핸들링 하고 있는가?(dailydev)',
    participates: 5,
    maxParticipates: 5,
    deadline: '2024-05-22T23:59:59',
    progress: false,
  },
  {
    id: 1017,
    docType: 'OFFICIAL',
    field: 'API',
    title: 'Fetch API, 너는 에러를 제대로 핸들링 하고 있는가?(dailydev)',
    participates: 10,
    maxParticipates: 10,
    deadline: '2024-11-22T23:59:59',
    progress: false,
  },
  {
    id: 1016,
    docType: 'BLOG',
    field: 'CAREER',
    title: '개발자로서 자신만의 브랜드를 구축하는 방법(dailydev)',
    participates: 5,
    maxParticipates: 5,
    deadline: '2024-02-22T23:59:59',
    progress: false,
  },
  {
    id: 1015,
    docType: 'BLOG',
    field: 'NEXTJS',
    title: 'Next.js - App Router: Routing Fundamentals',
    participates: 1,
    maxParticipates: 10,
    deadline: '2025-02-22T23:59:59',
    progress: false,
  },
  {
    id: 1014,
    docType: 'BLOG',
    field: 'NEXTJS',
    title: 'Next.js - App Router: Routing Fundamentals',
    participates: 10,
    maxParticipates: 10,
    deadline: '2024-02-22T23:59:59',
    progress: false,
  },
  {
    id: 2022,
    docType: 'OFFICIAL',
    field: 'NEXTJS',
    title: 'Next.js - App Router: Routing Fundamentals',
    participates: 10,
    maxParticipates: 20,
    deadline: '2024-11-10T23:59:59',
    progress: false,
  },
];